---
name: "TorrentPauser"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Short description about your plugin"
description: >
  Automatically limit QBittorrent client if someone starts watching something.
category: "General"
owner: "timothy1205"
artifacts:
  - "Jellyfin.Plugin.TorrentPauser.dll"
changelog: >
  ~
